### ISSUE TITLE
Automatic webpage build

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention#137]
@marvinroger Could you please add the environment variable TRAVIS_ACCESS_TOKEN to the repo on https://travis-ci.org/homieiot/convention/settings. A change on this repo will then trigger the convention-website repo to build.

An access token can be generated with `travis login && travis token` on the command line. Install the cli tool with `gem install travis`.

**Comment by davidgraeff** [comment]
Hm, without any access rights I cannot really tackle the current website build situation. Please activate all repositories including this one in travis (travis tells me this repo is not activated for example) and provide an access token for "convention-website" and another access token on "convention-website" for "homieiot.github.io".

**Comment by marvinroger** [comment]
Here's the thing: the new Travis CI Github App integration lives in https://travis-ci.com/homieiot/convention, whereas the "legacy" Travis is located at https://travis-ci.org/homieiot/convention/. This is messed up, as both websites had different environment variables.

So I disabled the legacy travis-ci.org repos, and enabled all travis-ci.com repos, so that we use the new GitHub App integration.

The `convention-website` now have the `GITHUB_TOKEN` env, and the `convention` has `TRAVIS_ACCESS_TOKEN`.

Let me know if it's OK now.

**Comment by davidgraeff** [comment]
No matter what I enter into the .travis.yml file within the develop branch, https://travis-ci.com/homieiot/convention/builds always only shows the "releaser" branch as active.

**Comment by davidgraeff** [comment]
Could you also completely remove the master branch? The develop branch would need the lock instead, but not right now while I'm still editing the travis file.
The idea is that everything needs to go in by a pull request and no direct commit to the develop branch, which already happened to me once.

**Comment by marvinroger** [comment]
@davidgraeff I removed the `master` branch.

Take a look: https://travis-ci.com/homieiot/convention/requests (`Could not parse .travis.yml`)

**Comment by davidgraeff** [comment]
Ah ok. The Requests tab is not visible for me.

**Comment by davidgraeff** [comment]
I have fixed the travis syntax. But I get an "access denied" by the curl command.
According to the travis api page: https://docs.travis-ci.com/user/triggering-builds/
the command itself should work.
I guess the access token you have generated does not allow triggering a build on "convention-website".

**Comment by marvinroger** [comment]
I refreshed the token, it should be alright. :)
