### ISSUE TITLE
Validator expects property attribute $type which is not defined?

### ISSUE THREAD

**Issue by andig** [homieiot/convention#139]
Publishing this property:

    homie/meter1/$homie 3.0.1
    homie/meter1/$name GoSDM
    homie/meter1/$state ready
    homie/meter1/$type meter
    homie/meter1/$nodes meter
    homie/meter1/meter/$name SDM
    homie/meter1/meter/$type meter
    homie/meter1/meter/$properties cosphil1
    homie/meter1/meter/cosphil1/$name L1 Cosphi

gives:

    Property 'cosphil1' requires '$name' and '$type' to be set!

Property attribute `$type` is not part of the spec and `$datatype` is optional.

Whats wrong here?

**Comment by davidgraeff** [comment]
The error message should be different, I agree. The topic is actually not part of homie (which enforces the homie/device/node/property layout)

**Comment by andig** [comment]
Sorry, I don‘t get it. Confusing message, validator error or wrong format published?

**Comment by davidgraeff** [comment]
"homie/meter1/meter/cosphil1/$name L1"
This is not a homie topic therefore the validator fails.
You have the base topic "homie", check. You have a node called "meter1", check. You've got a property called "meter", check. 
And then the validator struggles, because it expects a $name and $type for that property.
Instead you've got another topic sublevel called "cosphil1".

Oh. Does the spec call it $datatype? I thought it is $type only. I'll fix that.
However the type is mandatory at least in the development version of the spec, I think. I'll check that.

**Comment by timpur** [comment]
@davidgraeff, is the convention related ? 

If this is to do with an implementation, please open in the correct repo.

Edit:

May bad not am implementation, but i think this issue still should sit with https://github.com/homieiot/convention-website repo please

**Comment by andig** [comment]
> You have the base topic "homie", check. You have a node called "meter1", check. You've got a property called "meter", check.

@davidgraeff really appreciate your answers, thanks you! Looking at the spec for the thousands time it still doesn‘t connect with me. Spec says:

    homie / device ID / node ID / property ID

spec has this example:

    homie/super-car/engine/temperature

Isn‘t meter the node and cosphil1 the property? Why are you o itting the device?

**Comment by davidgraeff** [comment]
Oh, I shouldn't answer such a question past midnight, half-asleep. You are right. Your topic is fine.

**Comment by davidgraeff** [comment]
Fixed

**Comment by andig** [comment]
@davidgraeff tried again and still same result?

**Comment by davidgraeff** [comment]
Press F5 while on the tools page. The cache is overriding server responses.

**Comment by andig** [comment]
doh: Confirmed working, thank you!
