### ISSUE TITLE
Restructure spec

### ISSUE THREAD

**Issue by andig** [homieiot/convention#149]
After working with the spec a bit now I've found it a bit inaccessible in terms of "important things first". As-is:

1. Abstract
1. MQTT Restrictions
1. Base Topic
1. Timings
1. Extensions
1. Topology

I could imagine the following order would be easier to digest:

1. Abstract
1. Topology
1. Base Topic -> remove, this is already part of Topology
1. Extensions
1. Timings
1. MQTT Restrictions

if there's interest in this I'd be happy to do a PR.

**Comment by davidgraeff** [comment]
The website does not reflect the specification 1:1, so this issue is about the website generator.

Because homie has multiple versions, we decided that it makes sense to have a unified document preface which contains all MQTT restrictions, faq, and generic topics. 

This preface can of course also be appended instead of prepended.

**Comment by andig** [comment]
> The website does not reflect the specification 1:1, so this issue is about the website generator.

Note sure what that means: https://homieiot.github.io/specification/ claims to be the spec? Is there another one?

> Because homie has multiple versions, we decided that it makes sense to have a unified document preface which contains all MQTT restrictions, faq, and generic topics.

Totally! I'm just saying its hard to get the spirit of homie since the reading starts with technical details instead of the bigger picture.

Feel free to close or let me know if you want a PR.

**Comment by davidgraeff** [comment]
I have the same feeling actually, but if you read any scientific paper or IEEE specification or IETF specification, they all start with the preconditions (the boring parts). That's why I have the example on the landing page of the homie website.

I thought about maybe collapsing those parts, like it is done with the FAQ.

> Note sure what that means: https://homieiot.github.io/specification/ claims to be the spec? Is there another one?

The website generator takes all spec versions of this repo, generates a unified preface out of the latest version and generates a page for each version with the preface prepended. 
The preface sections are not the order as how they appear in the convention.md file here on the repo though. Extensions is at the end in the convention.md file for example, but because it is a preface section it moves to the front on the website.

**Comment by andig** [comment]
Closing as I didn‘t figure out a good approach to do this with the generator.
