### ISSUE TITLE
Protocol Buffer for the payload?

### ISSUE THREAD

**Issue by michcfr** [homieiot/convention#285]
Hello,
Is there any plan that Homie uses the Google Protocol Buffer for the payload?
It enable compact mqtt messages.
This is for example what Sparkplug mqtt is using. 

I don't know if it is a good idea, I just wanted to share and discuss about this opportunity.

Michel

**Comment by Tieske** [comment]
Not likely. The current draft for version 5 doesn't change the format, and if anything introduces some JSON elements (single topic device description).

It was discussed however, here's my recollection of why not;
- not available everywhere
- has a steeper learning curve, so harder to get started with
- not easy to debug for user nor developer (because of its binary nature)

**Comment by michcfr** [comment]
Thank you for the response.
The not makes sense. 
May we get access to the draft for version 5? Thx

**Comment by Tieske** [comment]
It's in the [homie5 branch](https://github.com/homieiot/convention/blob/homie5/convention.md)

**Comment by Thalhammer** [comment]
As already outlined by Tieske, protobuf has been discussed before and a decision has been made in favor of json, mostly because of its wide availability. Homie mostly uses mqtt topics for structure, so the only message that would really benefit from it is the description topic. As lined out by #287 we will likely add a binary type soonish, which means you can send arbitrary binary data there (including protobuf).

I personally would have loved to move to protobuf for its DSL and codegen features, but I have to agree, that especially in IoT devices json support is often already built in the firmware while pb would need extra space.

I assume this is resolved, if not feel free to reopen @michcfr.
