### ISSUE TITLE
Arrays got removed, but specification uses one as example

### ISSUE THREAD

**Issue by GrigoriOH** [homieiot/convention#290]
Hello there,

I am pretty new to homie and fell in love with this standard. While examining the specifications (https://homieiot.github.io/specification/) I noticed an array notation for node detection of light in chapter 7.1.1's example:

> homie/super-car/$nodes` → "wheels,engine,lights[]"

As there is no explanation about it, I dove in to this GitHub page and noticed, that Arrays got removed in v4.
To avoid confusion, maybe removing the array notation from the example might help new users like me :)

All the best, and thanks for your work!

**Comment by Tieske** [comment]
this was fixed a long time ago; https://github.com/homieiot/convention/commit/12453d851b85783dd5323430ce3aa85fcc376641

@Thalhammer I thought the the site was rendered again last year, after you made some changes. Am I wrong?

**Comment by Thalhammer** [comment]
The CI for the website should get triggered whenever someone pushes to the [homieiot.github.io](https://github.com/homieiot/homieiot.github.io) repo (or the workflow is manually triggered).
However it seems like it didn't run ever. I'll look into it.

EDIT: It seems like the reason it doesn't get included is because the versions on the website are generated by taking the tags. The fix for the example however was added after the tag for v4. Given the fix is in the commit that directly follows the release we could probably just force move the tag. Thats not a nice thing to do, but I doubt it would cause issues in this case.

However thats not scalable. Going forward we should probably switch to a "branch per version" model instead of just tags, so we can do cosmetic changes after releasing it.

**Comment by Tieske** [comment]
What if we tag a version 4.0.1, as a patch on the spec. Would that work?

A branch per major version usually does the job, though in this case `master` is still the one supporting `v4`, since there is no `v5` tagged yet. I also do not expect new changes coming into `v4`. So I think we should be good without the branches, since (as a spec type thing) it is essentially supposed to be a slow-moving project anyway.

**Comment by Thalhammer** [comment]
> Would that work?

Yes, but it would show up as a separate version in the website. I went ahead and force pushed/moved the tag by one commit. I'll update the website repo, so this should be fixed by that. Not sure how we wanna proceed with stuff like this in the future.

EDIT: Changes moved to website.

**Comment by Tieske** [comment]
in theory the site should only show major and minor versions; `4`, `4.1`, etc. Patches are not relevant for the spec-consumer, only for the maintainers. So we should fix the scripts probably to only render the latest patch version. (or we keep doing it manually as it is slow moving anyway 🤷 )

**Comment by Tieske** [comment]
I just checked, seems that older releases also have a 3.0.1 for example, but I think adding more might clutter it.

If we merge the v5 branch, would that then automatically show up under `[develop]`? If so, then I am tempted to do that. Wdyt @Thalhammer ?

**Comment by Thalhammer** [comment]
> So we should fix the scripts probably to only render the latest patch version.

If we are going to touch the scripts I'd vote for rewriting them from scratch, cause I don't really like the setup as it is right now. Its mostly a legacy written long before I got involved with the project.

> If we merge the v5 branch, would that then automatically show up under [develop]?

If I understand the python script correctly the v* ones are simply the list of tags on the repo and the develop one is whatever is currently in the develop branch. Note that the website will only update when a build is run on the website repo, which currently only happens when commits are pushed to master on the website repo. I am pretty sure there are options to trigger a build on it when there are changes on the convention repo, but I'll have to look that up.

EDIT: So yes if you merge the v5 branch into develop it will show up on the website. I haven't really kept track with what you guys have been doing lately, but `develop` being by definition an unstable branch I don't really see an issue with doing develop work on it.

**Comment by Tieske** [comment]
Done. merged v5. 🎉

**Comment by Tieske** [comment]
@Thalhammer I merged the v5 branch, but cannot manually run the deploy workflow. I presume because of permissions. Can you run the workflow? (or alternatively provide me with the permissions)

**Comment by Thalhammer** [comment]
> Can you run the workflow?

Done. I think the reason you couldn't rerun the ci is because it was triggered by my commit. I doubt there is a setting I can change to allow that. Ideally we should a action to this repo that automatically triggers a run in the website repo.

I'll close this issue cause its fixed. I suggest we open a new one for discussions about the CI if necessary or move it to matrix.
