### ISSUE TITLE
Broadcast: add a standardize way to get brodcast source

### ISSUE THREAD

**Issue by nicola-lunghi** [homieiot/convention#81]
When I receive a broadcast message in a lot of cases I want to know the source of the broadcast

For example 

change the broadcast topic format in this way

If for example the source of the message is 

    homie/super-car/lights

Instead of having it like this

    homie / $broadcast / level: level is an arbitrary broadcast identifier. It must adhere to the ID format.

have a topic like this

    homie / $broadcast / level/[source] where source is the source of the broadcast

for example

    homie / $broadcast/level/super-car/lights "message"

**Comment by fermuch** [comment]
I agree it might be needed sometimes to know the source of a broadcast, but in those cases why don't you just put it in the payload?

`homie/$broadcast/lights → '{"position": "front-right", "kind": "turned-on"}'`

**Comment by ingoogni** [comment]
Sorry, I don't get the problem. The whole mqtt string can be used to precisely pinpoint the source, especialy if you use a semantic string:
/car/electric/lights/front/right/main
/car/electric/lights/front/right/direction_indicator

**Comment by fermuch** [comment]
> Sorry, I don't get the problem. The whole mqtt string can be used to precisely pinpoint the source, especialy if you use a semantic string:
> /car/electric/lights/front/right/main
> /car/electric/lights/front/right/direction_indicator

This is not true for [broadcasts](https://github.com/homieiot/convention#broadcast-channel) since they only have a "level" variable, which can't contain slashes (`/`), since that isn't a valid ID character.

Although there's nothing saying you can't use sub-levels on the broadcast. I'm unsure if broadcasts are supposed to work only one level deep or they should be multi-level.

**Comment by fermuch** [comment]
At least on the esp8266 implementation, broadcasts seem to be only one level deep. See https://github.com/marvinroger/homie-esp8266/blob/99161ce03c7ff1c8d3dc1fcc52abbf081212b68f/src/Homie/Boot/BootNormal.cpp#L465

**Comment by ingoogni** [comment]
My understanding may be wrong, from the convention:
homie / $broadcast / level: level is an arbitrary broadcast identifier. It must adhere to the ID format. <links to:
> An MQTT topic consists of one or more topic levels, separated by the slash character (/). A topic level ID MAY contain lowercase letters from a to z, numbers from 0 to 9 as well as the hyphen character (-).

Though the implementation may differ, if so it may need some clarification here and there.

**Comment by nicola-lunghi** [comment]
Seems from the response that for a common problem like indicating the source of a broadcast everyone has a different solution: use json, use a topic, use another

that could lead for the same problem to different solutions.

Here is the utility of a convention: decide that to solve this problem the recomended way is one.

So If I make a device and you make a device you know that you will receive broadcast messages from the light object in the form

homie/$broadcast/my-home-87392798713921/light "light: on"

I don't search implementation (I was thinking myself to the json solution but that means including in the convention the prerequisite of sending json data... mmm no)

**Comment by nicola-lunghi** [comment]
The usefulness of the broadcast is that I don't need to know the specific topic a sensor is transmitting for.

an example use is for auto-discovery:
- a new light sensor is added to the system and want to publish the fact that is available
- it will publish a broadcast message in 

    homie/$broadcast/new-device/[id]/id front/lights/living-room
    homie/$broadcast/new-device/[id]/type light sensor
- then it will start sending data to his own mqtt topic
    homie/[id]

so a device can listen to the broadcast "new-device"channel and if sees something that is supporting can register to additional mqtt topics

Is a valid case?
how this should be implemented?

**Comment by euphi** [comment]
Yes, the broadcast mechanism is meant for information that is sent from the home automation controller to the devices. 

Homie is all about the state of properties of devices and their nodes, but not about the state of the network (and whatever it represents, e.g. a home or a garage full of super-cars ;-) .

There is nothing in the convention yet about how devices subscribe to information that may be interesting to them but are not directly linked to a property of the devices (and its nodes).
For now, broadcasts are a simple solution for the most important use cases.
E.g.

* Alerts
* Presence
* Maintenance/admin mode

I don't see auto-discovery as a use case, because this is a information from the Homie-device to the controller. So the controller (or anyone else interested in the network) can subscribe to `homie/+/$name` or `homie/+/+` to see new devices.

**Comment by davidgraeff** [comment]
To summarise:
* the source of a broadcast can be added to the actual broadcast message.
* broadcast messages are mostly send by controllers and they have no unique id in the homie network
* sub-topics to express the source are not a good idea, because mqtt does not guarantee the order of topic publishes.

Can I close this or is there any question left or proposal to make?
